/**
 * Multi-crop detect catalog for Myanmar field crops.
 * Labels are English canonical names used by AI detect + UI.
 * Full disease/pest lists per crop (field-guide coverage).
 */

export const CROP_TYPES = [
  'Rice',
  'Black Gram',
  'Green Gram',
  'Pigeon Pea',
  'Sesame',
  'Groundnut',
  'Sunflower',
  'Maize',
  'Rubber',
  'Sugarcane',
  'Cotton',
  'Cabbage',
  'Onion',
  'Garlic',
  'Chili',
  'Potato',
  'Tea',
  'Coffee',
  'Oil Palm',
] as const;

export type CropType = (typeof CROP_TYPES)[number];

export const CROP_NAME_MY: Record<CropType, string> = {
  Rice: 'စပါး',
  'Black Gram': 'မတ်ပဲ',
  'Green Gram': 'ပဲတီစိမ်း',
  'Pigeon Pea': 'ပဲစင်းငုံ',
  Sesame: 'နှမ်း',
  Groundnut: 'မြေပဲ',
  Sunflower: 'နေကြာ',
  Maize: 'ပြောင်းဖူး',
  Rubber: 'ရော်ဘာ',
  Sugarcane: 'ကြံ',
  Cotton: 'ဝါ',
  Cabbage: 'ဂေါ်ဖီထုပ်',
  Onion: 'ကြက်သွန်နီ',
  Garlic: 'ကြက်သွန်ဖြူ',
  Chili: 'ငရုတ်',
  Potato: 'အာလူး',
  Tea: 'လက်ဖက်',
  Coffee: 'ကော်ဖီ',
  'Oil Palm': 'ဆီအုန်း',
};

export function cropNameMy(crop?: string): string {
  if (!crop) return '';
  return CROP_NAME_MY[crop as CropType] || crop;
}

/** Per-crop diseases (excluding Healthy). */
export const CROP_DISEASES: Record<CropType, readonly string[]> = {
  Rice: [
    'Blast',
    'Bacterial Leaf Blight',
    'Sheath Blight',
    'Tungro',
    'Brown Spot',
    'Bakanae',
    'False Smut',
    'Sheath Rot',
    'Stem Rot',
    'Crown Rot',
    'Narrow Brown Spot',
    'Leaf Scald',
    'Yellow Dwarf Virus',
    'Grassy Stunt Virus',
    'Ragged Stunt Virus',
    'Black-Streaked Dwarf Virus',
    'Foot Rot',
    'Seedling Blight',
    'Kernel Smut',
    'Downy Mildew',
    'Leaf Smut',
    'Bacterial Leaf Streak',
  ],
  'Black Gram': [
    'Yellow Mosaic',
    'Powdery Mildew',
    'Root Rot',
    'Cercospora Leaf Spot',
    'Anthracnose',
    'Charcoal Rot',
    'Rust',
    'Web Blight',
    'Leaf Crinkle Virus',
    'Stem Rot',
    'Bacterial Leaf Spot',
    'Crown Rot',
    'Collar Rot',
    'Downy Mildew',
    'Damping Off',
  ],
  'Green Gram': [
    'Yellow Mosaic',
    'Powdery Mildew',
    'Cercospora Leaf Spot',
    'Charcoal Rot',
    'Anthracnose',
    'Web Blight',
    'Dry Root Rot',
    'Halo Blight',
    'Bacterial Leaf Spot',
    'Leaf Crinkle',
    'Leaf Curl Virus',
    'Macrophomina Blight',
    'Fusarium Wilt',
    'Rust',
    'Damping Off',
  ],
  'Pigeon Pea': [
    'Fusarium Wilt',
    'Sterility Mosaic',
    'Phytophthora Blight',
    'Alternaria Blight',
    'Macrophomina Root Rot',
    'Powdery Mildew',
    'Collar Rot',
    'Stem Canker',
    'Bacterial Leaf Spot',
    'Yellow Mosaic',
    'Dry Root Rot',
    'Phyllody',
    'Anthracnose',
    'Rust',
    'Cercospora Leaf Spot',
  ],
  Sesame: [
    'Phyllody',
    'Alternaria Leaf Spot',
    'Stem Rot',
    'Root Rot',
    'Bacterial Leaf Spot',
    'Cercospora Leaf Spot',
    'Powdery Mildew',
    'Phytophthora Blight',
    'Fusarium Wilt',
    'Leaf Curl Virus',
    'Charcoal Rot',
    'Damping Off',
    'Damping-Off Blight',
  ],
  Groundnut: [
    'Early Leaf Spot',
    'Late Leaf Spot',
    'Rust',
    'Crown Rot',
    'Peanut Stem Necrosis Virus',
    'Collar Rot',
    'Charcoal Rot',
    'Stem Rot',
    'Rosette Virus',
    'Peanut Mottle Virus',
    'Peanut Clump Virus',
    'Yellow Mold',
    'Bacterial Wilt',
    'Root Rot',
    'Pod Rot',
    'Cylindrocladium Black Rot',
  ],
  Sunflower: [
    'Alternaria Blight',
    'Rust',
    'Sclerotinia Head Rot',
    'Powdery Mildew',
    'Downy Mildew',
    'Verticillium Wilt',
    'Charcoal Rot',
    'Sunflower Necrosis Virus',
    'Rhizopus Head Rot',
    'Septoria Leaf Spot',
    'Bacterial Stalk Rot',
    'Stem Rot',
    'Collar Rot',
    'Phoma Black Stem',
    'Myrothecium Leaf Spot',
  ],
  Maize: [
    'Southern Leaf Blight',
    'Northern Leaf Blight',
    'Common Rust',
    'Downy Mildew',
    'Charcoal Rot',
    'Pythium Stalk Rot',
    'Fusarium Stalk Rot',
    'Head Smut',
    'Kernel Rot',
    'Banded Leaf and Sheath Blight',
    'Crazy Top Downy Mildew',
    'Bacterial Stalk Rot',
    'Maize Dwarf Mosaic Virus',
    'Corn Stunt',
    'Diplodia Ear Rot',
  ],
  Rubber: [
    'South American Leaf Blight',
    'Powdery Mildew',
    'Pink Disease',
    'Phytophthora Leaf Fall',
    'Abnormal Leaf Fall',
    'White Root Disease',
    'Red Root Disease',
    'Brown Root Disease',
    'Black Stripe',
    'Patch Canker',
    'Corynespora Leaf Spot',
    'Colletotrichum Leaf Fall',
    'Birds Eye Spot',
    'Thread Blight',
    'Dieback',
  ],
  Sugarcane: [
    'Red Rot',
    'Smut',
    'Grassy Shoot',
    'Wilt',
    'Pokkah Boeng',
    'Sett Rot',
    'Mosaic Virus',
    'Yellow Leaf',
    'Banded Sclerotial Disease',
    'Ratoon Stunting Disease',
    'Leaf Scald',
    'Red Stripe',
    'Rust',
    'Brown Spot',
    'Downy Mildew',
  ],
  Cotton: [
    'Bacterial Blight',
    'Fusarium Wilt',
    'Verticillium Wilt',
    'Alternaria Leaf Spot',
    'Cotton Leaf Curl Virus',
    'Root Rot',
    'Anthracnose',
    'Areolate Mildew',
    'Grey Mildew',
    'Cercospora Leaf Spot',
    'Stem Rot',
    'Boll Rot',
    'Myrothecium Leaf Spot',
    'Damping Off',
    'Crown Gall',
  ],
  Cabbage: [
    'Black Rot',
    'Clubroot',
    'Downy Mildew',
    'Alternaria Leaf Spot',
    'Powdery Mildew',
    'Wirestem',
    'Black Leg',
    'Damping Off',
    'Fusarium Yellows',
    'Sclerotinia Rot',
    'Soft Rot',
    'Mosaic Virus',
    'Ring Spot',
    'Anthracnose',
  ],
  Onion: [
    'Purple Blotch',
    'Stemphylium Blight',
    'Downy Mildew',
    'Basal Rot',
    'White Rot',
    'Neck Rot',
    'Black Mold',
    'Smut',
    'Anthracnose',
    'Twister Disease',
    'Fusarium Wilt',
    'Damping Off',
    'Iris Yellow Spot Virus',
    'Soft Rot',
    'Pink Root',
  ],
  Garlic: [
    'Purple Blotch',
    'White Rot',
    'Downy Mildew',
    'Rust',
    'Stemphylium Blight',
    'Basal Rot',
    'Mosaic Virus',
    'Penicillium Decay',
    'Black Rot',
    'Anthracnose',
    'Soft Rot',
    'Damping Off',
    'Fusarium Rot',
    'Yellow Dwarf Virus',
    'Neck Rot',
  ],
  Chili: [
    'Anthracnose',
    'Chilli Leaf Curl Virus',
    'Powdery Mildew',
    'Bacterial Wilt',
    'Cercospora Leaf Spot',
    'Fusarium Wilt',
    'Phytophthora Blight',
    'Damping Off',
    'Mosaic Virus',
    'Choanephora Blight',
    'Alternaria Leaf Spot',
    'Stem Rot',
    'Root Rot',
    'Mosaic Complex',
    'Crown Rot',
  ],
  Potato: [
    'Late Blight',
    'Early Blight',
    'Bacterial Wilt',
    'Common Scab',
    'Black Scurf',
    'Potato Virus Y',
    'Potato Leafroll Virus',
    'Potato Virus X',
    'Dry Rot',
    'Soft Rot',
    'Charcoal Rot',
    'Powdery Scab',
    'Wart Disease',
    'Gangrene',
    'Silver Scurf',
  ],
  Tea: [
    'Blister Blight',
    'Black Rot',
    'Red Rust',
    'Charcoal Stump Rot',
    'Brown Root Rot',
    'Red Root Rot',
    'Poria Root Disease',
    'Collar Rot',
    'Branch Canker',
    'Grey Blight',
    'Brown Blight',
    'Wood Rot',
    'Thorny Stem Blight',
    'Net Blight',
    'Dieback',
  ],
  Coffee: [
    'Coffee Leaf Rust',
    'Coffee Berry Disease',
    'Black Rot',
    'American Leaf Spot',
    'Brown Eye Spot',
    'Fusarium Bark Disease',
    'Ceratocystis Wilt',
    'Root Rot',
    'Pink Disease',
    'Anthracnose',
    'Damping Off',
    'Halo Blight',
    'Bacterial Blight',
    'Warty Disease',
    'Thread Blight',
  ],
  'Oil Palm': [
    'Ganoderma Basal Stem Rot',
    'Vascular Wilt',
    'Crown Disease',
    'Upper Stem Rot',
    'Bunch Rot',
    'Spear Rot',
    'Red Ring Disease',
    'Anthracnose',
    'Curvularia Leaf Spot',
    'Pestalotiopsis Leaf Spot',
    'Blast',
    'Root Rot',
    'Orange Spotting',
    'Phytophthora Pod Rot',
    'Seedling Blight',
  ],
};

/** Per-crop insect / mite / nematode / vertebrate pests. */
export const CROP_PESTS: Record<CropType, readonly string[]> = {
  Rice: [
    'Yellow Stem Borer',
    'Striped Stem Borer',
    'Dark-Headed Stem Borer',
    'White Stem Borer',
    'Pink Stem Borer',
    'Brown Planthopper',
    'Whitebacked Planthopper',
    'Green Leafhopper',
    'Zigzag Leafhopper',
    'Rice Gall Midge',
    'Rice Leaf Folder',
    'Rice Bug',
    'Rice Hispa',
    'Rice Armyworm',
    'Swarming Caterpillar',
    'Cutworm',
    'Rice Thrips',
    'Rice Caseworm',
    'Rice Skipper',
    'Rice Grasshopper',
    'Slender Rice Bug',
    'Whorl Maggot',
    'Mealybug',
    'Root Aphid',
    'Black Bug',
    'White Tip Nematode',
    'Rice Root-Knot Nematode',
    'Stem Nematode',
    'Rice Water Weevil',
    'Spider Mites',
  ],
  'Black Gram': [
    'Whitefly',
    'Pod Borer',
    'Aphids',
    'Thrips',
    'Spotted Pod Borer',
    'Leaf Hopper',
    'Blue Butterfly',
    'Stem Fly',
    'Hairy Caterpillar',
    'Red Spider Mite',
    'Bihar Hairy Caterpillar',
    'Blister Beetle',
    'Leaf Miner',
    'Bruchid Beetle',
    'Root-Knot Nematode',
  ],
  'Green Gram': [
    'Whitefly',
    'Pod Borer',
    'Aphids',
    'Spotted Pod Borer',
    'Thrips',
    'Stem Fly',
    'Leaf Hopper',
    'Red Hairy Caterpillar',
    'Bihar Hairy Caterpillar',
    'Tobacco Caterpillar',
    'Blue Butterfly',
    'Blister Beetle',
    'Leaf Miner',
    'Bruchid Beetle',
    'Mites',
  ],
  'Pigeon Pea': [
    'Gram Pod Borer',
    'Pod Fly',
    'Plume Moth',
    'Spotted Pod Borer',
    'Pod Bug',
    'Blister Beetle',
    'Jewel Bug',
    'Leaf Webber',
    'Leaf Hopper',
    'Thrips',
    'Red Spider Mite',
    'Scale Insect',
    'Bruchid Beetle',
    'Root-Knot Nematode',
    'White Grub',
  ],
  Sesame: [
    'Leaf and Pod Borer',
    'Gall Fly',
    'Sphinx Moth',
    'Aphids',
    'Jassid',
    'Whitefly',
    'Thrips',
    'Mirid Bug',
    'Pod Sucking Bug',
    'Red Spider Mite',
    'Leaf Hopper',
    'Cutworm',
    'Flea Beetle',
    'Root Grub',
    'Capsule Borer',
  ],
  Groundnut: [
    'Groundnut Leaf Miner',
    'Red Hairy Caterpillar',
    'White Grub',
    'Aphids',
    'Thrips',
    'Jassid',
    'Tobacco Caterpillar',
    'Jewel Beetle',
    'Pod Borer',
    'Termites',
    'Root-Knot Nematode',
    'Burrowing Nematode',
    'Wireworm',
    'Earwig',
    'Blister Beetle',
  ],
  Sunflower: [
    'Head Caterpillar',
    'Cutworm',
    'Jassid',
    'Whitefly',
    'Tobacco Caterpillar',
    'Bihar Hairy Caterpillar',
    'Thrips',
    'Aphids',
    'Leaf Hopper',
    'Seed Bug',
    'Mealybug',
    'Snout Beetle',
    'Red Spider Mite',
    'Stem Borer',
    'Wireworm',
  ],
  Maize: [
    'Fall Armyworm',
    'Maize Stem Borer',
    'Pink Stem Borer',
    'Shoot Fly',
    'Corn Earworm',
    'Aphids',
    'Flea Beetle',
    'White Grub',
    'Termites',
    'Wireworm',
    'Spider Mites',
    'Thrips',
    'Cutworm',
    'Grasshopper',
    'Corn Rootworm',
  ],
  Rubber: [
    'Scale Insect',
    'Mealybug',
    'Termites',
    'Yellow Mite',
    'Red Spider Mite',
    'Cockchafer Beetle',
    'Bark Eating Caterpillar',
    'Locusts',
    'Slugs',
    'Snails',
    'Nematodes',
    'White Grub',
    'Carpenter Bee',
    'Wood Borer',
    'Thrips',
    'Grasshopper',
  ],
  Sugarcane: [
    'Early Shoot Borer',
    'Top Borer',
    'Internode Borer',
    'Stalk Borer',
    'Root Borer',
    'Sugarcane Woolly Aphid',
    'Pyrilla',
    'Whitefly',
    'Mealybug',
    'Scale Insect',
    'Termites',
    'White Grub',
    'Armyworm',
    'Black Bug',
    'Mites',
  ],
  Cotton: [
    'American Bollworm',
    'Pink Bollworm',
    'Spotted Bollworm',
    'Spiny Bollworm',
    'Whitefly',
    'Jassid',
    'Aphids',
    'Thrips',
    'Tobacco Caterpillar',
    'Red Cotton Bug',
    'Dusky Cotton Bug',
    'Cotton Stem Weevil',
    'Leaf Roller',
    'Red Spider Mite',
    'Mealybug',
  ],
  Cabbage: [
    'Diamondback Moth',
    'Cabbage Head Caterpillar',
    'Cabbage Butterfly',
    'Aphids',
    'Flea Beetle',
    'Cabbage Looper',
    'Cutworm',
    'Thrips',
    'Cabbage Webworm',
    'Painted Bug',
    'Tobacco Caterpillar',
    'Root Maggot',
    'Armyworm',
    'Snails',
    'Slugs',
    'Root-Knot Nematode',
  ],
  Onion: [
    'Onion Thrips',
    'Onion Maggot',
    'Cutworm',
    'Armyworm',
    'Leaf Miner',
    'Red Spider Mite',
    'Root Aphid',
    'Wireworm',
    'Bulb Mite',
    'Stem and Bulb Nematode',
  ],
  Garlic: [
    'Thrips',
    'Eriophyid Mite',
    'Stem and Bulb Nematode',
    'Root Maggot',
    'Cutworm',
    'Wireworm',
    'Leaf Miner',
    'Armyworm',
    'Bulb Mite',
    'Aphids',
  ],
  Chili: [
    'Chilli Thrips',
    'Yellow Mite',
    'Whitefly',
    'Aphids',
    'Tobacco Caterpillar',
    'Fruit Borer',
    'Root-Knot Nematode',
    'Broad Mite',
    'Leaf Miner',
    'Mealybug',
    'Cutworm',
    'Grasshopper',
    'Termites',
    'Pod Borer',
    'Flea Beetle',
  ],
  Potato: [
    'Potato Tuber Moth',
    'Colorado Potato Beetle',
    'Aphids',
    'Cutworm',
    'White Grub',
    'Flea Beetle',
    'Potato Leafhopper',
    'Thrips',
    'Wireworm',
    'Root-Knot Nematode',
    'Cyst Nematode',
    'Broad Mite',
    'Blister Beetle',
    'Armyworm',
    'Slugs',
  ],
  Tea: [
    'Tea Mosquito Bug',
    'Shot Hole Borer',
    'Red Spider Mite',
    'Pink Mite',
    'Scarlet Mite',
    'Purple Mite',
    'Thrips',
    'Tea Looper',
    'Flushworm',
    'Leaf Roller',
    'Tea Tortrix',
    'Scale Insect',
    'Aphids',
    'Termites',
    'Root-Knot Nematode',
  ],
  Coffee: [
    'Coffee Berry Borer',
    'White Stem Borer',
    'Mealybug',
    'Green Scale',
    'Red Borer',
    'Shot Hole Borer',
    'Black Twig Borer',
    'Leaf Miner',
    'Antestia Bug',
    'Coffee Thrips',
    'Root Mealybug',
    'Spider Mites',
    'Caterpillars',
    'Root-Knot Nematode',
    'Termites',
  ],
  'Oil Palm': [
    'Rhinoceros Beetle',
    'Nettle Caterpillar',
    'Bagworm',
    'Bunch Moth',
    'Red Palm Weevil',
    'Termites',
    'Mealybug',
    'Scale Insect',
    'Mites',
    'Grasshopper',
    'Armyworm',
    'Rats',
    'Porcupines',
    'Wild Boars',
    'Birds',
  ],
};

/** @deprecated Prefer CROP_DISEASES.Rice + Healthy */
export const RICE_DISEASES = [...CROP_DISEASES.Rice, 'Healthy'] as const;
export type RiceDisease = (typeof RICE_DISEASES)[number];

/** @deprecated Prefer CROP_PESTS.Rice */
export const RICE_PESTS = CROP_PESTS.Rice;
export type RicePest = (typeof RICE_PESTS)[number];

/** Flat allowlist for AI detect (unique) + Healthy. */
function uniqueLabels(lists: readonly (readonly string[])[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const list of lists) {
    for (const item of list) {
      if (!seen.has(item)) {
        seen.add(item);
        out.push(item);
      }
    }
  }
  return out;
}

export const ALL_DETECT_LABELS = [
  ...uniqueLabels([...Object.values(CROP_DISEASES), ...Object.values(CROP_PESTS)]),
  'Healthy',
] as const;

export type DetectLabel = (typeof ALL_DETECT_LABELS)[number];

/** Labels allowed for a given crop (plus Healthy). */
export function labelsForCrop(crop: string): string[] {
  const key = crop as CropType;
  if (!CROP_DISEASES[key]) return [...ALL_DETECT_LABELS];
  return [...CROP_DISEASES[key], ...CROP_PESTS[key], 'Healthy'];
}

/** @deprecated Onion standalone list — use CROP_DISEASES.Onion */
export const ONION_DISEASES = CROP_DISEASES.Onion;
export type OnionDisease = (typeof ONION_DISEASES)[number];

/**
 * Myanmar display names for diseases & pests.
 * Unknown labels fall back to English via diseaseNameMy().
 */
export const DISEASE_NAME_MY: Record<string, string> = {
  Blast: 'စပါးဂုတ်ကျိုးရောဂါ',
  'Brown Spot': 'ရွက်ညိုပြောက်ရောဂါ',
  'Bacterial Leaf Blight': 'ဘက်တီးရီးယားရွက်ခြောက်ရောဂါ',
  'Sheath Blight': 'ရွက်ဖုံးခြောက်ရောဂါ',
  'Leaf Scald': 'ရွက်လောင်ရောဂါ',
  'Leaf Smut': 'ရွက်မှိုမဲရောဂါ',
  Tungro: 'တန်ဂရိုရောဂါ',
  'False Smut': 'စပါးမှိုသီးရောဂါ',
  'Narrow Brown Spot': 'ရွက်ညိုပြောက်ရှည်ရောဂါ',
  'Bacterial Leaf Streak': 'ဘက်တီးရီးယားရွက်စင်းရောဂါ',
  'Sheath Rot': 'ရွက်ဖုံးပုပ်ရောဂါ',
  Bakanae: 'ပင်ရှည်ရောဂါ',
  'Stem Rot': 'ပင်စည်ပုပ်ရောဂါ',
  'Crown Rot': 'အမောက်ပုပ်ရောဂါ',
  'Yellow Dwarf Virus': 'အဝါရောင် ပုညှိုးဗိုင်းရပ်စ်',
  'Grassy Stunt Virus': 'မြက်ပုံ ပုညှိုးဗိုင်းရပ်စ်',
  'Ragged Stunt Virus': 'ရွက်စုတ် ပုညှိုးဗိုင်းရပ်စ်',
  'Black-Streaked Dwarf Virus': 'မည်းအစင်း ပုညှိုးဗိုင်းရပ်စ်',
  'Foot Rot': 'ခြေရင်းပုပ်ရောဂါ',
  'Seedling Blight': 'ပျိုးပင်ပုပ်ရောဂါ',
  'Kernel Smut': 'စပါးစေ့မှိုမဲ',
  'Downy Mildew': 'အောက်မှုန့်မှိုရောဂါ',
  'Yellow Mosaic': 'အဝါရောင် မိုစေးခ်ရောဂါ',
  'Cercospora Leaf Spot': 'ဆာကိုစပိုရာ ရွက်ပြောက်',
  'Powdery Mildew': 'မှုန့်မှိုရောဂါ',
  Anthracnose: 'အန်သရာခနို့စ်ရောဂါ',
  'Root Rot': 'အမြစ်ပုပ်ရောဂါ',
  Rust: 'သံချေးရောဂါ',
  'Bacterial Leaf Spot': 'ဘက်တီးရီးယား ရွက်ပြောက်',
  Wilt: 'ညှိုးရောဂါ',
  'Sterility Mosaic': 'မျိုးမအောင် မိုစေးခ်',
  'Phytophthora Blight': 'ဖိုင်တိုဖသိုရာ ပုပ်ရောဂါ',
  'Stem Canker': 'ပင်စည်အနာရောဂါ',
  'Web Blight': 'ပင့်ကူအိမ်ပုပ်ရောဂါ',
  Phyllody: 'အရွက်ပွင့်ရောဂါ',
  'Alternaria Leaf Spot': 'အော်တာနေးရီးယား ရွက်ပြောက်',
  'Charcoal Rot': 'မီးသွေးပုပ်ရောဂါ',
  'Early Leaf Spot': 'အစောပိုင်း ရွက်ပြောက် (တိက္ကာ)',
  'Late Leaf Spot': 'နောက်ကျ ရွက်ပြောက် (တိက္ကာ)',
  'Collar Rot': 'လည်ပင်းပုပ်ရောဂါ',
  'Leaf Crinkle Virus': 'ရွက်တွန့်ဗိုင်းရပ်စ်',
  'Leaf Crinkle': 'ရွက်တွန့်ရောဂါ',
  'Leaf Curl Virus': 'ရွက်လိပ်ဗိုင်းရပ်စ်',
  'Damping Off': 'ပျိုးပင်လဲရောဂါ',
  'Damping-Off Blight': 'ပျိုးပင်လဲပုပ်ရောဂါ',
  'Dry Root Rot': 'အခြောက်အမြစ်ပုပ်',
  'Halo Blight': 'အဝိုင်းအနား ရွက်ပြောက်',
  'Macrophomina Blight': 'မက်ခရိုဖိုမီနာ ပုပ်',
  'Fusarium Wilt': 'ဖူစေရီယမ် ညှိုးရောဂါ',
  'Macrophomina Root Rot': 'မက်ခရိုဖိုမီနာ အမြစ်ပုပ်',
  'Alternaria Blight': 'အော်တာနေးရီးယား ပုပ်ရောဂါ',
  'Peanut Stem Necrosis Virus': 'မြေပဲပင်စည် သေဗိုင်းရပ်စ်',
  'Rosette Virus': 'ရိုဆက်ဗိုင်းရပ်စ်',
  'Peanut Mottle Virus': 'မြေပဲအစက်ဗိုင်းရပ်စ်',
  'Peanut Clump Virus': 'မြေပဲပုညှိုးဗိုင်းရပ်စ်',
  'Yellow Mold': 'အဝါရောင်မှို',
  'Bacterial Wilt': 'ဘက်တီးရီးယား ညှိုးရောဂါ',
  'Pod Rot': 'အိတ်ပုပ်ရောဂါ',
  'Cylindrocladium Black Rot': 'ဆီလင်ဒရိုကလာဒီယမ် မည်းပုပ်',
  'Sclerotinia Head Rot': 'စကလီရိုတီးနီးယား ခေါင်းပုပ်',
  'Verticillium Wilt': 'ဗာတီစီလီယမ် ညှိုးရောဂါ',
  'Sunflower Necrosis Virus': 'နေကြာ သေဗိုင်းရပ်စ်',
  'Rhizopus Head Rot': 'ရိုင်ဇိုပပ်စ် ခေါင်းပုပ်',
  'Septoria Leaf Spot': 'ဆက်တိုရီးယား ရွက်ပြောက်',
  'Bacterial Stalk Rot': 'ဘက်တီးရီးယား ပင်စည်ပုပ်',
  'Phoma Black Stem': 'ဖိုမာ မည်းပင်စည်',
  'Myrothecium Leaf Spot': 'မိုင်ရိုသီစီယမ် ရွက်ပြောက်',
  'Northern Leaf Blight': 'မြောက်ပိုင်း ရွက်ခြောက် (Turcicum)',
  'Southern Leaf Blight': 'တောင်ပိုင်း ရွက်ခြောက် (Maydis)',
  'Common Rust': 'သာမန် သံချေးရောဂါ',
  'Pythium Stalk Rot': 'ပိုင်သီယမ် ပင်စည်ပုပ်',
  'Fusarium Stalk Rot': 'ဖူစေရီယမ် ပင်စည်ပုပ်',
  'Head Smut': 'ခေါင်းမှိုမဲ',
  'Kernel Rot': 'စပါး/စေ့ပုပ်',
  'Banded Leaf and Sheath Blight': 'အစင်းရွက်နှင့် ရွက်ဖုံးပုပ်',
  'Crazy Top Downy Mildew': 'ခရေဇီတော့ အောက်မှုန့်မှို',
  'Maize Dwarf Mosaic Virus': 'ပြောင်း ပုညှိုးမိုစေးခ်',
  'Corn Stunt': 'ပြောင်းပုညှိုးရောဂါ',
  'Diplodia Ear Rot': 'ဒီပလိုဒီယာ အနှံပုပ်',
  'South American Leaf Blight': 'တောင်အမေရိက ရွက်ခြောက်',
  'Pink Disease': 'ပန်းရောင်ရောဂါ',
  'Phytophthora Leaf Fall': 'ဖိုင်တိုဖသိုရာ ရွက်ကြွေ',
  'Abnormal Leaf Fall': 'ပုံမှန်မဟုတ် ရွက်ကြွေ',
  'White Root Disease': 'အဖြူအမြစ်ရောဂါ',
  'Red Root Disease': 'နီရောင်အမြစ်ရောဂါ',
  'Brown Root Disease': 'ညိုရောင်အမြစ်ရောဂါ',
  'Black Stripe': 'မည်းအစင်းရောဂါ',
  'Patch Canker': 'အစက်အနာရောဂါ',
  'Corynespora Leaf Spot': 'ကိုရိုင်နက်စပိုရာ ရွက်ပြောက်',
  'Colletotrichum Leaf Fall': 'ကိုလက်တိုထရစ်ခမ် ရွက်ကြွေ',
  'Birds Eye Spot': 'ငှက်မျက်လုံးပြောက်',
  'Thread Blight': 'ချည်မျှင်ပုပ်ရောဂါ',
  Dieback: 'အဖျားသေရောဂါ',
  'Red Rot': 'နီရောင်ပုပ်ရောဂါ',
  Smut: 'မှိုမဲရောဂါ',
  'Grassy Shoot': 'မြက်ညွန့်ရောဂါ',
  'Pokkah Boeng': 'ပိုခါဘောင်းရောဂါ',
  'Sett Rot': 'အပင်ပိုင်းပုပ်',
  'Mosaic Virus': 'မိုစေးခ်ဗိုင်းရပ်စ်',
  'Yellow Leaf': 'ရွက်ဝါရောဂါ',
  'Banded Sclerotial Disease': 'အစင်း စကလီရိုရှယ် ရောဂါ',
  'Ratoon Stunting Disease': 'ရိတ်ပြန်ပင် ပုညှိုးရောဂါ',
  'Red Stripe': 'နီရောင်အစင်း',
  'Bacterial Blight': 'ဘက်တီးရီးယား ခြောက်ရောဂါ',
  'Cotton Leaf Curl Virus': 'ဝါရွက်လိပ်ဗိုင်းရပ်စ်',
  'Areolate Mildew': 'အရီအိုလိတ် မှိုရောဂါ',
  'Grey Mildew': 'မီးခိုးရောင် မှိုရောဂါ',
  'Boll Rot': 'အိတ်ပုပ်ရောဂါ',
  'Crown Gall': 'အမောက်အကျိတ်ရောဂါ',
  'Black Rot': 'မည်းပုပ်ရောဂါ',
  Clubroot: 'အမြစ်ဖောင်းရောဂါ',
  Wirestem: 'ကြိုးပင်စည်ရောဂါ',
  'Black Leg': 'ခြေမည်းရောဂါ',
  'Fusarium Yellows': 'ဖူစေရီယမ် အဝါရောဂါ',
  'Sclerotinia Rot': 'စကလီရိုတီးနီးယား ပုပ် (အဖြူမှို)',
  'Soft Rot': 'ပျော့ပုပ်ရောဂါ',
  'Ring Spot': 'ကွင်းပြောက်ရောဂါ',
  'Purple Blotch': 'ခရမ်းရောင် အစက်ရောဂါ',
  'Stemphylium Blight': 'စတမ်ဖီလီယမ် ပုပ်ရောဂါ',
  'Basal Rot': 'အခြေပုပ်ရောဂါ',
  'White Rot': 'အဖြူပုပ်ရောဂါ',
  'Neck Rot': 'လည်ပင်းပုပ်ရောဂါ',
  'Black Mold': 'မည်းမှိုရောဂါ',
  'Twister Disease': 'လိမ်ရောဂါ',
  'Iris Yellow Spot Virus': 'အိုင်ရစ် အဝါပြောက်ဗိုင်းရပ်စ်',
  'Pink Root': 'ပန်းရောင်အမြစ်',
  'Penicillium Decay': 'ပင်နီဆီလီယမ် ပုပ်',
  'Fusarium Rot': 'ဖူစေရီယမ် ပုပ်',
  'Chilli Leaf Curl Virus': 'ငရုတ်ရွက်လိပ်ဗိုင်းရပ်စ်',
  'Choanephora Blight': 'ချိုနီဖိုရာ ပုပ်ရောဂါ',
  'Mosaic Complex': 'မိုစေးခ်ပေါင်းစုံ',
  'Late Blight': 'နောက်ကျ ပုပ်ရောဂါ',
  'Early Blight': 'အစောပိုင်း ပုပ်ရောဂါ',
  'Black Scurf': 'မည်းအနာရောဂါ',
  'Common Scab': 'သာမန် အနာဖေး',
  'Potato Virus Y': 'အာလူးဗိုင်းရပ်စ် Y',
  'Potato Leafroll Virus': 'အာလူး ရွက်လိပ်ဗိုင်းရပ်စ်',
  'Potato Virus X': 'အာလူးဗိုင်းရပ်စ် X',
  'Dry Rot': 'အခြောက်ပုပ်',
  'Powdery Scab': 'မှုန့်အနာဖေး',
  'Wart Disease': 'အကျိတ်ရောဂါ',
  Gangrene: 'ဂန်ဂရင်းပုပ်',
  'Silver Scurf': 'ငွေရောင်အနာ',
  'Blister Blight': 'အရည်ကြည်ဖု ရောဂါ',
  'Charcoal Stump Rot': 'မီးသွေးပင်ခြေပုပ်',
  'Brown Root Rot': 'ညိုရောင်အမြစ်ပုပ်',
  'Red Root Rot': 'နီရောင်အမြစ်ပုပ်',
  'Poria Root Disease': 'ပိုရီယာ အမြစ်ရောဂါ',
  'Branch Canker': 'အကိုင်းအနာ',
  'Grey Blight': 'မီးခိုးရောင် ပုပ်',
  'Brown Blight': 'ညိုရောင် ပုပ်',
  'Wood Rot': 'သစ်သားပုပ်',
  'Thorny Stem Blight': 'ဆူးပင်စည်ပုပ်',
  'Net Blight': 'ကွန်ရက်ပုပ်',
  'Red Rust': 'နီရောင် သံချေး',
  'Coffee Leaf Rust': 'ကော်ဖီရွက် သံချေး',
  'Coffee Berry Disease': 'ကော်ဖီသီး ရောဂါ',
  'American Leaf Spot': 'အမေရိကန် ရွက်ပြောက်',
  'Brown Eye Spot': 'ညိုရောင် မျက်လုံးပြောက်',
  'Fusarium Bark Disease': 'ဖူစေရီယမ် အခေါက်ရောဂါ',
  'Ceratocystis Wilt': 'စီရတိုစစ်တစ်စ် ညှိုး',
  'Warty Disease': 'အကျိတ်ရောဂါ',
  'Ganoderma Basal Stem Rot': 'ဂါနိုဒါမာ ပင်ခြေပုပ်',
  'Vascular Wilt': 'သွေးကြောညှိုးရောဂါ',
  'Crown Disease': 'အမောက်ရောဂါ',
  'Upper Stem Rot': 'ပင်အပေါ်ပုပ်',
  'Bunch Rot': 'အနှံပုပ်',
  'Spear Rot': 'အလယ်ရွက်ပုပ်',
  'Red Ring Disease': 'နီရောင်ကွင်းရောဂါ',
  'Curvularia Leaf Spot': 'ကာဗူလာရီးယား ရွက်ပြောက်',
  'Pestalotiopsis Leaf Spot': 'ပက်စတလိုတီအော့စစ် ရွက်ပြောက်',
  'Orange Spotting': 'လိမ္မော်အစက်',
  'Phytophthora Pod Rot': 'ဖိုင်တိုဖသိုရာ အိတ်ပုပ်',
  // Pests
  'Yellow Stem Borer': 'စပါးပင်စည်ထိုးပိုး',
  'Striped Stem Borer': 'အစင်း ပင်စည်ထိုးပိုး',
  'Dark-Headed Stem Borer': 'ခေါင်းမည်း ပင်စည်ထိုးပိုး',
  'White Stem Borer': 'ပင်စည်ထိုးပိုးဖြူ',
  'Pink Stem Borer': 'ပန်းရောင် ပင်စည်ထိုးပိုး',
  'Brown Planthopper': 'အညိုရောင် ပင်စည်ခုန်ပိုး',
  'Whitebacked Planthopper': 'အဖြူကျော ပင်စည်ခုန်ပိုး',
  'Green Leafhopper': 'စပါးရွက်စိမ်းခုန်ပိုး',
  'Zigzag Leafhopper': 'ဇစ်ဇတ် ရွက်ခုန်ပိုး',
  'Rice Gall Midge': 'စပါးဂေါ်လ်မစ်ပိုး',
  'Rice Leaf Folder': 'စပါးရွက်လိပ်ပိုး',
  'Rice Bug': 'စပါးနှံစုပ်ပိုး',
  'Rice Hispa': 'စပါးဟစ်စပါပိုး',
  'Rice Armyworm': 'စပါးတပ်ပိုး',
  'Swarming Caterpillar': 'အုပ်စုလိုက် ပိုးလောက်',
  Cutworm: 'ဖြတ်ပိုး',
  'Rice Thrips': 'စပါးသရစ်ပိုး',
  'Rice Caseworm': 'စပါးအိတ်ပိုး',
  'Rice Skipper': 'စပါးခုန်ပိုးလိပ်ပြာ',
  'Rice Grasshopper': 'စပါးကျိုင်း',
  'Slender Rice Bug': 'စပါးနှံစုပ်ပိုးကျဉ်း',
  'Whorl Maggot': 'စပါးပင်ထိပ်ယင်ပိုး',
  Mealybug: 'ဂွမ်းပိုး',
  'Root Aphid': 'အမြစ်ပိုးမွှား',
  'Black Bug': 'ပိုးမည်း',
  'White Tip Nematode': 'အဖျားဖြူ နီမတုတ်',
  'Rice Root-Knot Nematode': 'စပါးအမြစ်ဖု နီမတုတ်',
  'Stem Nematode': 'ပင်စည် နီမတုတ်',
  'Rice Water Weevil': 'စပါးရေပိုးစား',
  'Spider Mites': 'ပင့်ကူမှဲ့',
  'Pod Borer': 'အိတ်ထိုးပိုး',
  Aphids: 'ပိုးမွှားစိမ်း',
  Whitefly: 'ယင်ဖြူ',
  Thrips: 'သရစ်ပိုး',
  'Leaf Hopper': 'ရွက်ခုန်ပိုး',
  'Bruchid Beetle': 'ပဲပိုးကောင်',
  'Spotted Pod Borer': 'အစက်အိတ်ထိုးပိုး',
  'Blue Butterfly': 'ပြာပိုးလိပ်ပြာ',
  'Stem Fly': 'ပင်စည်ယင်',
  'Hairy Caterpillar': 'အမွေးပိုးလောက်',
  'Red Spider Mite': 'ပင့်ကူနီ',
  'Bihar Hairy Caterpillar': 'ဘီဟာ အမွေးပိုးလောက်',
  'Blister Beetle': 'အရည်ကြည်ပိုး',
  'Leaf Miner': 'ရွက်ထိုးပိုး',
  'Root-Knot Nematode': 'အမြစ်ဖု နီမတုတ်',
  'Red Hairy Caterpillar': 'အမွေးနီပိုးလောက်',
  'Tobacco Caterpillar': 'ဆေးရွက်ကြီး ပိုးလောက်',
  Mites: 'မှဲ့ပိုး',
  'Gram Pod Borer': 'ပဲအိတ်ထိုးပိုး',
  'Pod Fly': 'အိတ်ယင်',
  'Plume Moth': 'ပလူးမော့',
  'Pod Bug': 'အိတ်ပိုး',
  'Jewel Bug': 'ရတနာပိုး',
  'Leaf Webber': 'ရွက်အိမ်ပိုး',
  'Scale Insect': 'အကြေးပိုး',
  'White Grub': 'မြေပိုးလောက်ဖြူ',
  'Leaf and Pod Borer': 'ရွက်နှင့်အိတ်ထိုးပိုး',
  'Gall Fly': 'ဂေါ်လ်ယင်',
  'Sphinx Moth': 'စဖင်းစ် ပိုးလိပ်ပြာ',
  Jassid: 'ဂျက်ဆစ်ပိုး',
  'Mirid Bug': 'မီရစ်ပိုး',
  'Pod Sucking Bug': 'အိတ်စုပ်ပိုး',
  'Flea Beetle': 'ခုန်ပိုး',
  'Root Grub': 'အမြစ်ပိုးလောက်',
  'Capsule Borer': 'အိတ်ထိုးပိုး',
  'Groundnut Leaf Miner': 'မြေပဲ ရွက်ထိုးပိုး',
  'Jewel Beetle': 'ရတနာပိုးကောင်',
  Termites: 'ပိုးဟပ်',
  'Burrowing Nematode': 'မြေတွင်း နီမတုတ်',
  Wireworm: 'ကြိုးပိုး',
  Earwig: 'နားရွက်ပိုး',
  'Head Caterpillar': 'ခေါင်းပိုးလောက်',
  'Seed Bug': 'မျိုးစေ့ပိုး',
  'Snout Beetle': 'နှာရှည်ပိုး',
  'Stem Borer': 'ပင်စည်ထိုးပိုး',
  'Fall Armyworm': 'ဖောလ်တပ်ပိုး',
  'Maize Stem Borer': 'ပြောင်းပင်စည်ထိုးပိုး',
  'Shoot Fly': 'အညွန့်ယင်',
  'Corn Earworm': 'ပြောင်းအနှံပိုး',
  Grasshopper: 'ကျိုင်း',
  'Corn Rootworm': 'ပြောင်းအမြစ်ပိုး',
  'Yellow Mite': 'အဝါရောင်မှဲ့',
  'Cockchafer Beetle': 'ကော့ခ်ချက်ဖာ ပိုး',
  'Bark Eating Caterpillar': 'အခေါက်စား ပိုးလောက်',
  Locusts: 'ကျိုင်းကြီး',
  Slugs: 'ပက်ကျိ',
  Snails: 'ခရု',
  Nematodes: 'နီမတုတ်',
  'Carpenter Bee': 'လက်သမားပျား',
  'Wood Borer': 'သစ်ထိုးပိုး',
  'Early Shoot Borer': 'အစောပိုင်း အညွန့်ထိုးပိုး',
  'Top Borer': 'ထိပ်ထိုးပိုး',
  'Internode Borer': 'ဆစ်ကြားထိုးပိုး',
  'Stalk Borer': 'ပင်စည်ထိုးပိုး',
  'Root Borer': 'အမြစ်ထိုးပိုး',
  'Sugarcane Woolly Aphid': 'ကြံ သိုးမွေးပိုးမွှား',
  Pyrilla: 'ပိုင်ရီလာပိုး',
  Armyworm: 'တပ်ပိုး',
  'American Bollworm': 'အမေရိကန် ဝါအိတ်ပိုး',
  'Pink Bollworm': 'ပန်းရောင် အိတ်ပိုး',
  'Spotted Bollworm': 'အစက် အိတ်ပိုး',
  'Spiny Bollworm': 'ဆူး အိတ်ပိုး',
  'Red Cotton Bug': 'ဝါပိုးနီ',
  'Dusky Cotton Bug': 'ဝါပိုးမှောင်',
  'Cotton Stem Weevil': 'ဝါပင်စည် ပိုးစား',
  'Leaf Roller': 'ရွက်လိပ်ပိုး',
  'Diamondback Moth': 'စိန်ကျော ပိုးလိပ်ပြာ',
  'Cabbage Head Caterpillar': 'ဂေါ်ဖီခေါင်း ပိုးလောက်',
  'Cabbage Butterfly': 'ဂေါ်ဖီ ပိုးလိပ်ပြာ',
  'Cabbage Looper': 'ဂေါ်ဖီ ကွင်းပိုး',
  'Cabbage Webworm': 'ဂေါ်ဖီ အိမ်ပိုး',
  'Painted Bug': 'ဆေးရောင်ပိုး',
  'Root Maggot': 'အမြစ်ပိုးလောက်',
  'Onion Thrips': 'ကြက်သွန် သရစ်ပိုး',
  'Onion Maggot': 'ကြက်သွန် ပိုးလောက်',
  'Bulb Mite': 'ဥမှဲ့',
  'Stem and Bulb Nematode': 'ပင်စည်နှင့်ဥ နီမတုတ်',
  'Eriophyid Mite': 'အဲရီအိုဖိုက်မှဲ့',
  'Chilli Thrips': 'ငရုတ် သရစ်ပိုး',
  'Fruit Borer': 'သီးထိုးပိုး',
  'Broad Mite': 'ကျယ်မှဲ့',
  'Potato Tuber Moth': 'အာလူးဥ ပိုးလိပ်ပြာ',
  'Colorado Potato Beetle': 'ကိုလိုရာဒို အာလူးပိုး',
  'Potato Leafhopper': 'အာလူး ရွက်ခုန်ပိုး',
  'Cyst Nematode': 'စစ်စ် နီမတုတ်',
  'Tea Mosquito Bug': 'လက်ဖက် ခြင်ပိုး',
  'Shot Hole Borer': 'အပေါက်ထိုးပိုး',
  'Pink Mite': 'ပန်းရောင်မှဲ့',
  'Scarlet Mite': 'နီရဲမှဲ့',
  'Purple Mite': 'ခရမ်းရောင်မှဲ့',
  'Tea Looper': 'လက်ဖက် ကွင်းပိုး',
  Flushworm: 'အညွန့်ပိုး',
  'Tea Tortrix': 'လက်ဖက် တော့ထရစ်',
  'Coffee Berry Borer': 'ကော်ဖီသီး ထိုးပိုး',
  'Green Scale': 'စိမ်းအကြေးပိုး',
  'Red Borer': 'နီရောင်ထိုးပိုး',
  'Black Twig Borer': 'အကိုင်းမည်း ထိုးပိုး',
  'Antestia Bug': 'အန်တက်စတီးယားပိုး',
  'Coffee Thrips': 'ကော်ဖီ သရစ်ပိုး',
  'Root Mealybug': 'အမြစ်ဂွမ်းပိုး',
  Caterpillars: 'ပိုးလောက်များ',
  'Rhinoceros Beetle': 'ကြံ့ပိုး',
  'Nettle Caterpillar': 'အမွှေးနာ ပိုးလောက်',
  Bagworm: 'အိတ်ပိုး',
  'Bunch Moth': 'အနှံပိုးလိပ်ပြာ',
  'Red Palm Weevil': 'အုန်းပိုးနီ',
  Rats: 'ကြွက်',
  Porcupines: 'ပေါ်ကျူပိုင်း',
  'Wild Boars': 'တောဝက်',
  Birds: 'ငှက်',
  Healthy: 'ကျန်းမာသည်',
};

export function diseaseNameMy(disease: string): string {
  return DISEASE_NAME_MY[disease] || disease;
}

/** Prompt-friendly crop → problems summary for the vision model. */
export function cropProblemsPromptBlock(): string {
  return CROP_TYPES.map((crop) => {
    const diseases = CROP_DISEASES[crop].join(', ');
    const pests = CROP_PESTS[crop].join(', ');
    return `- ${crop} (${CROP_NAME_MY[crop]}): diseases [${diseases}]; pests [${pests}]`;
  }).join('\n');
}
